### ISSUE TITLE
Implement recursion for p_throws and p_type

### ISSUE THREAD

**Issue by jrbattles** [fire-ants/mlb-machine-learning#4]

**Comment by goyetc** [comment]
Note: I think this issue needs to be more fully defined. I suspect that this issue is intended to address the way we *iterate* through available pitch types. The goal is to dynamically pull this data rather than hard code pitch types? E.g., for pitch in pitch_type: if count(pitch) > y, then include in model

**Comment by jrbattles** [comment]
I actually intended to create this issue in mlb-analytics-ant.
